// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AButton: typeof import("ant-design-vue/es")["Button"];
    ARadioButton: typeof import("ant-design-vue/es")["RadioButton"];
    ARadioGroup: typeof import("ant-design-vue/es")["RadioGroup"];
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    Test: typeof import("./src/components/tset")["default"];
  }
}
