// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AAutoComplete: typeof import("ant-design-vue/es")["AutoComplete"];
    AButton: typeof import("ant-design-vue/es")["Button"];
    ACard: typeof import("ant-design-vue/es")["Card"];
    ACheckbox: typeof import("ant-design-vue/es")["Checkbox"];
    ACheckboxGroup: typeof import("ant-design-vue/es")["CheckboxGroup"];
    ACol: typeof import("ant-design-vue/es")["Col"];
    ADatePicker: typeof import("ant-design-vue/es")["DatePicker"];
    ADrawer: typeof import("ant-design-vue/es")["Drawer"];
    AEmpty: typeof import("ant-design-vue/es")["Empty"];
    AForm: typeof import("ant-design-vue/es")["Form"];
    AFormItem: typeof import("ant-design-vue/es")["FormItem"];
    AInput: typeof import("ant-design-vue/es")["Input"];
    AInputSearch: typeof import("ant-design-vue/es")["InputSearch"];
    AModal: typeof import("ant-design-vue/es")["Modal"];
    APagination: typeof import("ant-design-vue/es")["Pagination"];
    APopconfirm: typeof import("ant-design-vue/es")["Popconfirm"];
    ARadio: typeof import("ant-design-vue/es")["Radio"];
    ARadioGroup: typeof import("ant-design-vue/es")["RadioGroup"];
    ARow: typeof import("ant-design-vue/es")["Row"];
    ASelect: typeof import("ant-design-vue/es")["Select"];
    ASpin: typeof import("ant-design-vue/es")["Spin"];
    ASwitch: typeof import("ant-design-vue/es")["Switch"];
    ATable: typeof import("ant-design-vue/es")["Table"];
    ATabPane: typeof import("ant-design-vue/es")["TabPane"];
    ATabs: typeof import("ant-design-vue/es")["Tabs"];
    ATextarea: typeof import("ant-design-vue/es")["Textarea"];
    ATooltip: typeof import("ant-design-vue/es")["Tooltip"];
    ATreeSelect: typeof import("ant-design-vue/es")["TreeSelect"];
    AUpload: typeof import("ant-design-vue/es")["Upload"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
